spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    password: root
    username: root
    url: jdbc:mysql://localhost:8080/website
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    change-log: liquibase-changeLog.xml